name: CI

on: workflow_dispatch

jobs:
  ci:
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    continue-on-error: true

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v3

      - name: Analyze 1
        id: analyze1
        uses: ./
        with:
          api-key: ${{ secrets.API_KEY }}
          domain-or-url: securityheaders.com

      - name: Verify 1
        env:
          RESULTS_AS_JSON: ${{ steps.analyze1.outputs.results-as-json }}
          SUMMARY_AS_JSON: ${{ steps.analyze1.outputs.summary-as-json }}
          GRADE: ${{ steps.analyze1.outputs.grade }}
        run: |
          echo "RESULTS_AS_JSON: [$RESULTS_AS_JSON]"
          echo "SUMMARY_AS_JSON: [$SUMMARY_AS_JSON]"
          echo "GRADE: [$GRADE]"

      - name: Analyze 2
        id: analyze2
        uses: ./
        with:
          api-key: ${{ secrets.API_KEY }}
          domain-or-url: securityheaders.com
          follow-redirects: false
          hide-results-on-homepage: false
          expected-grade: "R"

      - name: Verify 2
        env:
          RESULTS_AS_JSON: ${{ steps.analyze2.outputs.results-as-json }}
          SUMMARY_AS_JSON: ${{ steps.analyze2.outputs.summary-as-json }}
          GRADE: ${{ steps.analyze2.outputs.grade }}
        run: |
          jq '.' <<<"$SUMMARY_AS_JSON"

      - name: Analyze 3
        id: analyze3
        uses: ./
        with:
          api-key: ${{ secrets.API_KEY }}
          domain-or-url: securityheaders.com
          follow-redirects: false
          hide-results-on-homepage: false
          expected-grade: "R"

      - name: Verify 3
        env:
          RESULTS_AS_JSON: ${{ steps.analyze3.outputs.results-as-json }}
          SUMMARY_AS_JSON: ${{ steps.analyze3.outputs.summary-as-json }}
          GRADE: ${{ steps.analyze3.outputs.grade }}
        run: |
          jq '.' <<<"$SUMMARY_AS_JSON"

      - name: Analyze 4
        id: analyze4
        uses: ./
        with:
          api-key: ${{ secrets.API_KEY }}
          domain-or-url: securityheaders.com
          api-timeout-in-seconds: 1
          max-retries-on-api-error: 2

      - name: Verify 4
        env:
          RESULTS_AS_JSON: ${{ steps.analyze4.outputs.results-as-json }}
          SUMMARY_AS_JSON: ${{ steps.analyze4.outputs.summary-as-json }}
          GRADE: ${{ steps.analyze4.outputs.grade }}
        run: |
          jq '.' <<<"$SUMMARY_AS_JSON"
